Repository redux-form/redux-form, pull requests merged in 2020-04, with the labels that each got.

#4557 prevent shipping eval sourcemaps in UMD bundle
  webpack.config.js
Labels: performance

#4652 fix(v8): improve `SubmissionError` detection
  .size-limit.json
  src/SubmissionError.js
  src/__tests__/Form.spec.js
  src/__tests__/SubmissionError.spec.js
  src/__tests__/handleSubmit.spec.js
  src/__tests__/reduxForm.spec.js
  src/handleSubmit.js
  src/immutable.js
  src/index.js
Labels: Version 8

#4653 fix(v7): improve `SubmissionError` detection
  package-lock.json
  src/SubmissionError.js
  src/__tests__/SubmissionError.spec.js
  src/actions.js
  src/handleSubmit.js
Labels: Version 7
